### ISSUE TITLE
Face theme 'linto' not found

### ISSUE THREAD

**Issue by highness28** [linto-ai/jarvis#1]
### Description

Français and English are allowed.
Detailed description of your problem.
In case of feature request, please provide justification & example of usage.

### Logs
```shell
[{"error":"ERROR: face theme 'linto' not found"},{"warning":"HELP: verify pg_face_theme in jarvis-face plugin config"}]

plugins_enabled/jarvis-face/hooks/program_exit: line 1: pg_face_state: command not found
```
full content of the terminal with Jarvis in troubleshooting mode
(keep triple quotes above and below to preserve formatting) 

Alternatively attach a terminal session recording using asciinema:
```shell
sudo apt-get install -y asciinema && asciinema rec # start session recording
./jarvish.sh -nv # start jarvis directly in troubleshooting mode
Ctrl+D # stop recording
y # yes to upload and get URL to paste here
```

**Comment by damienlaine** [comment]
This repo is no longer maintained. Open Jarvis was a way of mocking up the LinTO client and is no longer part of LinTO project.
This repo, Jarvis forked from https://openjarvis.com/ is now archived.
